#!/usr/bin/env bash
# copyright © 2025-2026 bkey inc. all rights reserved.
#
# Generates src/lib/build-info.ts with the current git commit and build date.
# Called automatically by `npm run build` and `npm run dev`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${CLI_DIR}/src/lib/build-info.ts"

COMMIT=$(git -C "${CLI_DIR}" rev-parse --short HEAD 2>/dev/null || echo "dev")
DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "${OUT}" << EOF
// copyright © 2025-2026 bkey inc. all rights reserved.
//
// Auto-generated by scripts/gen-build-info.sh — do not edit manually.

export const BUILD_COMMIT = '${COMMIT}';
export const BUILD_DATE = '${DATE}';
EOF
