// copyright © 2025-2026 bkey inc. all rights reserved.
//
// Auto-generated by scripts/gen-build-info.sh — do not edit manually.

export const BUILD_COMMIT = '4b1019f';
export const BUILD_DATE = '2026-04-13T21:50:25Z';
