"""BKey vault store / access with client-side E2EE decryption.

Two subcommands:

  store <name> <value>
      Store a secret in the vault under the given name.

      NOTE: The current Python SDK sends the value plaintext over TLS to
      the BKey API. For fully client-side E2EE at rest today, use the
      TypeScript CLI (``bkey vault store``) or ``@bkey/sdk``.

  access <name>
      Request access to a stored secret. BKey pushes a biometric approval
      prompt to the user's phone; on approval, the server encrypts the
      secret to an *ephemeral* X25519 public key generated by this process,
      and this script decrypts it locally. The plaintext never leaves the
      machine that holds the private key.
"""

from __future__ import annotations

import argparse
import base64
import os
import sys
from typing import Any

import requests
from nacl.public import Box, PrivateKey, PublicKey

from bkey import BKeyClient
from bkey.exceptions import ApprovalDeniedError, ApprovalTimeoutError, BKeyError


def _require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        print(f"error: {name} is not set — see .env.example", file=sys.stderr)
        sys.exit(2)
    return value


def _client_and_base_url() -> tuple[BKeyClient, str]:
    client_id = _require_env("BKEY_CLIENT_ID")
    client_secret = _require_env("BKEY_CLIENT_SECRET")
    base_url = os.environ.get("BKEY_API_URL", "https://api.bkey.id").rstrip("/")
    client = BKeyClient(client_id=client_id, client_secret=client_secret, base_url=base_url)
    return client, base_url


def cmd_store(args: argparse.Namespace) -> int:
    client, _ = _client_and_base_url()
    try:
        resp = client.vault_store(key=args.name, value=args.value)
    except BKeyError as err:
        print(f"error: vault_store failed: {err}", file=sys.stderr)
        return 1
    print(f"==> stored: id={resp.id} status={resp.status}")
    print(
        "    note: the Python SDK currently sends the value plaintext over TLS. "
        "For client-side E2EE at rest, use @bkey/sdk or the `bkey` CLI."
    )
    return 0


def cmd_access(args: argparse.Namespace) -> int:
    client, base_url = _client_and_base_url()

    # Generate a fresh ephemeral X25519 keypair for *this* access attempt.
    # The server will encrypt the returned ciphertext to our public key;
    # only this process (which holds the matching private key) can decrypt.
    # A new keypair per access means a compromise of one session's private
    # key cannot be used to decrypt ciphertext from any other session.
    sk = PrivateKey.generate()
    ephemeral_public_key_b64 = base64.b64encode(bytes(sk.public_key)).decode("ascii")

    # Authenticate with the SDK, then send our ephemeral public key on the
    # access request. The SDK's ``vault_access()`` doesn't yet accept an
    # ephemeral key, so we hit the endpoint directly while re-using the
    # SDK's auth for the token exchange and its polling loop for status.
    token = client.authenticate().access_token
    try:
        resp = requests.post(
            f"{base_url}/v1/vault/{args.name}/access",
            headers={"Authorization": f"Bearer {token}"},
            json={"ephemeralPublicKey": ephemeral_public_key_b64},
            timeout=30,
        )
        resp.raise_for_status()
    except requests.HTTPError as err:
        print(f"error: access request failed: {err}", file=sys.stderr)
        print(f"        response: {resp.text}", file=sys.stderr)
        return 1
    except requests.RequestException as err:
        print(f"error: access request failed: {err}", file=sys.stderr)
        return 1

    access = resp.json()
    item_id = access.get("id", args.name)
    print(f"==> access requested: id={item_id}")
    print("    approve on your phone …")

    try:
        result = client.vault_poll(item_id, timeout=args.timeout)
    except ApprovalDeniedError:
        print("==> rejected by user", file=sys.stderr)
        return 1
    except ApprovalTimeoutError as err:
        print(f"==> timed out: {err}", file=sys.stderr)
        return 1
    except BKeyError as err:
        print(f"error: vault_poll failed: {err}", file=sys.stderr)
        return 1

    data: Any = result.data
    if not isinstance(data, dict):
        # Non-E2EE response: print whatever came back.
        print(f"==> {result.status}")
        if data is not None:
            print(data)
        return 0

    ciphertext_b64 = data.get("e2eeCiphertext")
    server_pk_b64 = data.get("serverPublicKey") or data.get("ephemeralPublicKey")
    if not ciphertext_b64 or not server_pk_b64:
        # Server did not return E2EE payload; fall back to printing data.
        print(f"==> {result.status}")
        print(data)
        return 0

    try:
        box = Box(sk, PublicKey(base64.b64decode(server_pk_b64)))
        plaintext = box.decrypt(base64.b64decode(ciphertext_b64))
    except Exception as err:  # noqa: BLE001 — surface any decrypt failure
        print(f"error: decryption failed: {err}", file=sys.stderr)
        return 1

    print(f"==> {result.status}")
    sys.stdout.buffer.write(plaintext)
    sys.stdout.write("\n")
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bkey-vault-access",
        description=(
            "BKey vault example. Stores a secret and retrieves it only after "
            "biometric approval on the user's phone, with client-side X25519 "
            "decryption of the returned ciphertext."
        ),
    )
    sub = parser.add_subparsers(dest="command", required=True)

    store = sub.add_parser("store", help="Store a secret under a name.")
    store.add_argument("name", help="Vault item name (unique per vault).")
    store.add_argument("value", help="Secret value to store.")
    store.set_defaults(func=cmd_store)

    access = sub.add_parser("access", help="Request access to a stored secret.")
    access.add_argument("name", help="Name of the vault item to read.")
    access.add_argument(
        "--timeout",
        type=int,
        default=120,
        help="Seconds to wait for biometric approval (default: %(default)s).",
    )
    access.set_defaults(func=cmd_access)

    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
